In [44]:
## Imports

import pandas as pd
import numpy as np
import cv2, os, glob, random

In [45]:
## Data imports

usrFolder = os.path.expanduser('~')
mainFolder = os.path.join(usrFolder,'Desktop','archive')
foldsPath = os.path.join(mainFolder,'Folds.csv')
dataPath = os.path.join(mainFolder,'BreaKHis_v1')

In [71]:
# Dataframe Assigning

folds = pd.read_csv(foldsPath)


# add filename for each sample in new column
folds["path"] = dataPath + os.sep + folds["filename"]

# extract information from each sample filename
meta = folds["filename"].str.extract(
    r"(SOB_(?P<cls>[BM])_(?P<subtype>[A-Z]+)-(?P<patient>\d+-[0-9A-Z]+)-\d+-\d+\.png$)"
)
folds = folds.join(meta)

# turn M and B into 1 and 0, respectively
folds["diagnosis"] = (folds["cls"] == "M").astype(int)


splits = {}

# segment data into folds, then into test/train. Assign this data to splits df
for k, fold_df in folds.groupby("fold"):
    temp = {}
    for grp, g in fold_df.groupby("grp"):
        temp[grp] = g
    splits[k] = temp


# Assign new test/training dataframes for each fold

test_df_1 = splits[1]["test"]
test_df_2 = splits[2]["test"]
test_df_3 = splits[3]["test"]
test_df_4 = splits[4]["test"]
test_df_5 = splits[5]["test"]

train_df_1 = splits[1]["train"]
train_df_2 = splits[2]["train"]
train_df_3 = splits[3]["train"]
train_df_4 = splits[4]["train"]
train_df_5 = splits[5]["train"]

In [73]:
train_df_1

,fold,mag,grp,filename,path,0,cls,subtype,patient,diagnosis
0,1,100,train,BreaKHis_v1/histology_slides/breast/benign/SOB...,/Users/gusrutledge/Desktop/archive/BreaKHis_v1...,SOB_B_A-14-22549AB-100-001.png,B,A,14-22549AB,0
1,1,100,train,BreaKHis_v1/histology_slides/breast/benign/SOB...,/Users/gusrutledge/Desktop/archive/BreaKHis_v1...,SOB_B_A-14-22549AB-100-002.png,B,A,14-22549AB,0
2,1,100,train,BreaKHis_v1/histology_slides/breast/benign/SOB...,/Users/gusrutledge/Desktop/archive/BreaKHis_v1...,SOB_B_A-14-22549AB-100-003.png,B,A,14-22549AB,0
3,1,100,train,BreaKHis_v1/histology_slides/breast/benign/SOB...,/Users/gusrutledge/Desktop/archive/BreaKHis_v1...,SOB_B_A-14-22549AB-100-004.png,B,A,14-22549AB,0
4,1,100,train,BreaKHis_v1/histology_slides/breast/benign/SOB...,/Users/gusrutledge/Desktop/archive/BreaKHis_v1...,SOB_B_A-14-22549AB-100-005.png,B,A,14-22549AB,0
...,...,...,...,...,...,...,...,...,...,...
5000,1,400,train,BreaKHis_v1/histology_slides/breast/malignant/...,/Users/gusrutledge/Desktop/archive/BreaKHis_v1...,SOB_M_PC-15-190EF-400-011.png,M,PC,15-190EF,1
5001,1,400,train,BreaKHis_v1/histology_slides/breast/malignant/...,/Users/gusrutledge/Desktop/archive/BreaKHis_v1...,SOB_M_PC-15-190EF-400-012.png,M,PC,15-190EF,1
5002,1,400,train,BreaKHis_v1/histology_slides/breast/malignant/...,/Users/gusrutledge/Desktop/archive/BreaKHis_v1...,SOB_M_PC-15-190EF-400-013.png,M,PC,15-190EF,1
5003,1,400,train,BreaKHis_v1/histology_slides/breast/malignant/...,/Users/gusrutledge/Desktop/archive/BreaKHis_v1...,SOB_M_PC-15-190EF-400-014.png,M,PC,15-190EF,1
5004,1,400,train,BreaKHis_v1/histology_slides/breast/malignant/...,/Users/gusrutledge/Desktop/archive/BreaKHis_v1...,SOB_M_PC-15-190EF-400-015.png,M,PC,15-190EF,1

,fold,mag,grp,filename,path,0,cls,subtype,patient,label
31636,5,100,train,BreaKHis_v1/histology_slides/breast/benign/SOB...,/Users/gusrutledge/Desktop/archive/BreaKHis_v1...,SOB_B_A-14-22549G-100-001.png,B,A,14-22549G,0
31637,5,100,train,BreaKHis_v1/histology_slides/breast/benign/SOB...,/Users/gusrutledge/Desktop/archive/BreaKHis_v1...,SOB_B_A-14-22549G-100-002.png,B,A,14-22549G,0
31638,5,100,train,BreaKHis_v1/histology_slides/breast/benign/SOB...,/Users/gusrutledge/Desktop/archive/BreaKHis_v1...,SOB_B_A-14-22549G-100-003.png,B,A,14-22549G,0
31639,5,100,train,BreaKHis_v1/histology_slides/breast/benign/SOB...,/Users/gusrutledge/Desktop/archive/BreaKHis_v1...,SOB_B_A-14-22549G-100-004.png,B,A,14-22549G,0
31640,5,100,train,BreaKHis_v1/histology_slides/breast/benign/SOB...,/Users/gusrutledge/Desktop/archive/BreaKHis_v1...,SOB_B_A-14-22549G-100-005.png,B,A,14-22549G,0
...,...,...,...,...,...,...,...,...,...,...
39540,5,400,test,BreaKHis_v1/histology_slides/breast/malignant/...,/Users/gusrutledge/Desktop/archive/BreaKHis_v1...,SOB_M_PC-15-190EF-400-011.png,M,PC,15-190EF,1
39541,5,400,test,BreaKHis_v1/histology_slides/breast/malignant/...,/Users/gusrutledge/Desktop/archive/BreaKHis_v1...,SOB_M_PC-15-190EF-400-012.png,M,PC,15-190EF,1
39542,5,400,test,BreaKHis_v1/histology_slides/breast/malignant/...,/Users/gusrutledge/Desktop/archive/BreaKHis_v1...,SOB_M_PC-15-190EF-400-013.png,M,PC,15-190EF,1
39543,5,400,test,BreaKHis_v1/histology_slides/breast/malignant/...,/Users/gusrutledge/Desktop/archive/BreaKHis_v1...,SOB_M_PC-15-190EF-400-014.png,M,PC,15-190EF,1
39544,5,400,test,BreaKHis_v1/histology_slides/breast/malignant/...,/Users/gusrutledge/Desktop/archive/BreaKHis_v1...,SOB_M_PC-15-190EF-400-015.png,M,PC,15-190EF,1